In [ ]:
from random import choices, seed
values = [1, 2, 3, 4, 5, 6]
seed(0)
print(sum([sum(choices(values, k=10)) >=50 for_in range (100000)])/100000)

In [13]:
values = [1, 2, 3, 4, 5, 6]
#values
n = 100000

In [23]:
from random import choices, seed

In [77]:
from random import choices, seed

#seed(0)

genie = 50

arr =[]

for i in range(0, n):
    arr.append(sum(choices(values, k=10)))

In [78]:
print(arr[:5])

[34, 29, 34, 31, 35]

In [79]:
n_arr = []

for i in arr:
    n_arr.append(i >= genie)

In [80]:
#true =1 and false = 0
sum(n_arr)/n

0.00327

In [204]:
#from random import choices, seed
#v1 = [3.47, 3.51, 3.54, 3.58, 3.62, 3.64, 3.65, 3.68, 3.71] ; lt = len(v1)
#v2 = [3.41, 3.42, 3.44, 3.45, 3.46, 3.51, 3.54, 3.63, 3.64] ; n = 100000 ; alpha = 0.01
#diff = sum(v1)/lt - sum(v2)/lt ; print(round(diff, 5))
#seed(0) ; stds = sorted([sum(choices(v1, k=lt))/lt - sum(choices(v2, k=lt))/lt for _ in range(n)])
#print('[', round(stds[int(n*alpha/2)], 5), ',', round(stds[n - int(n*alpha/2)], 5), ']')

In [205]:
v1 = [3.47, 3.51, 3.54, 3.58, 3.62, 3.64, 3.65, 3.68, 3.71]
v2 = [3.41, 3.42, 3.44, 3.45, 3.46, 3.51, 3.54, 3.63, 3.64]

In [206]:
mean1 = sum(v1)/len(v1)
mean1

3.5999999999999996

In [207]:
mean2 = sum(v2) / len(v2)
mean2

3.4999999999999996

In [208]:
mean_diff = mean1 - mean2
mean_diff

0.10000000000000009

In [209]:
print("%.g" % mean_diff)

0.1

In [210]:
from random import choices, seed

In [211]:
n=100000

In [212]:
def mean_list_diff(a,b):
    mean1 = sum(a)/len(a)
    mean1 = sum(b)/len(b)
    mean_diff = mean1 - mean2
    return mean_diff

In [213]:
boot_arr= []
for i in range (n):
    boot_v1 = choices(v1, k=len(v1))
    boot_v2 = choices(v2, k=len(v2))
    boot_arr.append (mean_list_diff(boot_v2, boot_v1))

In [214]:
alpha = 0.01

In [215]:
sorted_boot_arr = sorted(boot_arr)

In [218]:
left_side = int(len(sorted_boot_arr) * alpha/2)
right_side = int(len(sorted_boot_arr) * (1 - alpha/2))

In [220]:
ls = sorted_boot_arr[left_side]
rs = sorted_boot_arr[right_side]

print ("[", round(ls, 5), ",", round(rs, 5), "]")

[ 0.03444 , 0.16222 ]

In [223]:
def calc_ci(a):
    left_side = int(len(sorted_boot_arr) * alpha/2)
    right_side = int(len(sorted_boot_arr) * (1 - alpha/2))
    ls = sorted_boot_arr[left_side]
    rs = sorted_boot_arr[right_side]
    ci = [ls, rs]
    return ci

In [234]:
ci_dict = {}
for alpha in [0.001, 0.01, 0.05]:
    ci_dict[alpha] = calc_ci(alpha)

In [236]:
alpha = 0.001
ci_dict[alpha]

[0.01888888888888962, 0.1755555555555568]

In [330]:
url = "https://bioinfo.iric.ca/~feghalya/rnaseqclass_2024/hypoxiaDataset.complete.csv"

In [331]:
import pandas as pd

In [332]:
df = pd.read_csv(url)

In [333]:
df

,Id,norm.5.0-O2-n1,norm.5.0-O2-n2,norm.0.1-O2-n1,norm.0.1-O2-n2,norm.0.5-O2-n1,norm.0.5-O2-n2,norm.1.0-O2-n1,norm.1.0-O2-n2,5-O2,0.1-O2,0.5-O2,1-O2,pvalue,padj
0,gene0_Xkr4,0,0,0,0,1,1,0,0,0,0,1,0,1.000000,NaN
1,gene1_Gm18956,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN
2,gene100_Sulf1,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN
3,gene1000_Rhbdd1,4847,5299,4505,4850,4587,5854,4445,4579,5073,4678,5220,4512,0.451766,0.726399
4,gene10000_Ermap,6,0,2,0,2,0,0,2,3,1,1,1,0.566416,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15089,gene999_Irs1,1878,1391,1927,2388,2932,1651,1491,956,1634,2158,2292,1224,0.134217,0.392658
15090,gene9990_Gm12856,515,585,813,618,780,475,752,566,550,716,628,659,0.146007,0.410514
15091,gene9997_Slc2a1,16758,14628,21291,32525,19904,23827,16493,19999,15693,26908,21866,18246,0.000085,0.002734
15092,gene9998_Mir1957a,25,24,13,46,15,24,16,29,24,30,20,22,0.708969,0.880329
15093,gene9999_Zfp691,304,232,290,307,207,328,218,325,268,298,268,272,0.617136,0.832899

In [334]:
significant_pvalue = df[df["padj"] < 0.01]
significant_pvalue

,Id,norm.5.0-O2-n1,norm.5.0-O2-n2,norm.0.1-O2-n1,norm.0.1-O2-n2,norm.0.5-O2-n1,norm.0.5-O2-n2,norm.1.0-O2-n1,norm.1.0-O2-n2,5-O2,0.1-O2,0.5-O2,1-O2,pvalue,padj
25,gene10037_Ctps,5141,5519,8411,7669,7614,6353,6617,5176,5330,8040,6984,5896,3.042842e-04,7.218138e-03
51,gene10125_Fhl3,485,379,1235,1582,1327,819,420,637,432,1408,1073,528,1.850043e-10,4.361187e-08
59,gene10134_1110065P20Rik,1656,1645,2309,2508,2023,2304,1913,1823,1650,2408,2164,1868,2.435376e-04,6.238118e-03
112,gene10242_C77080,2177,1840,621,881,1095,1434,1211,2144,2008,751,1264,1678,5.386840e-08,5.975827e-06
136,gene10285_Tinagl1,4808,3619,17673,23864,23859,14605,7335,7516,4214,20768,19232,7426,1.649419e-24,2.262253e-21
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14949,gene967_Utp14b,2904,2616,1765,1516,1709,1517,2078,2527,2760,1640,1613,2302,8.378473e-06,4.389098e-04
15004,gene9788_Ttc39aos1,66,71,221,269,226,196,115,90,68,245,211,102,9.192766e-09,1.249471e-06
15035,gene9888_Pik3r3,11631,10191,5624,5268,4977,6165,6920,7135,10911,5446,5571,7028,3.740950e-11,1.045180e-08
15067,gene993_Dock10,490,578,259,110,273,128,254,289,534,184,200,272,4.763652e-05,1.748643e-03
15091,gene9997_Slc2a1,16758,14628,21291,32525,19904,23827,16493,19999,15693,26908,21866,18246,8.480340e-05,2.733822e-03

In [335]:
#df_subset = significant_pvalue.iloc[:,1:15]
#df_subset.head()

In [336]:
#remove the gene[xxx]£_ suffix from ID column for each row, keeping only the gene name (usinge stackoverflow)
#keep only the samples (including 2 replicates each), i.e., the ones woth the normalizes values

In [337]:
def extract_gene_names(gene_names) :
    return gene_names.split('_')[1]

significant_pvalue.loc[:,"Id"] = significant_pvalue["Id"].apply(extract_gene_names)
significant_pvalue

,Id,norm.5.0-O2-n1,norm.5.0-O2-n2,norm.0.1-O2-n1,norm.0.1-O2-n2,norm.0.5-O2-n1,norm.0.5-O2-n2,norm.1.0-O2-n1,norm.1.0-O2-n2,5-O2,0.1-O2,0.5-O2,1-O2,pvalue,padj
25,Ctps,5141,5519,8411,7669,7614,6353,6617,5176,5330,8040,6984,5896,3.042842e-04,7.218138e-03
51,Fhl3,485,379,1235,1582,1327,819,420,637,432,1408,1073,528,1.850043e-10,4.361187e-08
59,1110065P20Rik,1656,1645,2309,2508,2023,2304,1913,1823,1650,2408,2164,1868,2.435376e-04,6.238118e-03
112,C77080,2177,1840,621,881,1095,1434,1211,2144,2008,751,1264,1678,5.386840e-08,5.975827e-06
136,Tinagl1,4808,3619,17673,23864,23859,14605,7335,7516,4214,20768,19232,7426,1.649419e-24,2.262253e-21
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14949,Utp14b,2904,2616,1765,1516,1709,1517,2078,2527,2760,1640,1613,2302,8.378473e-06,4.389098e-04
15004,Ttc39aos1,66,71,221,269,226,196,115,90,68,245,211,102,9.192766e-09,1.249471e-06
15035,Pik3r3,11631,10191,5624,5268,4977,6165,6920,7135,10911,5446,5571,7028,3.740950e-11,1.045180e-08
15067,Dock10,490,578,259,110,273,128,254,289,534,184,200,272,4.763652e-05,1.748643e-03
15091,Slc2a1,16758,14628,21291,32525,19904,23827,16493,19999,15693,26908,21866,18246,8.480340e-05,2.733822e-03

In [338]:
normalized = significant_pvalue.loc[:, "Id":"norm.1.0-O2-n2"]
normalized

,Id,norm.5.0-O2-n1,norm.5.0-O2-n2,norm.0.1-O2-n1,norm.0.1-O2-n2,norm.0.5-O2-n1,norm.0.5-O2-n2,norm.1.0-O2-n1,norm.1.0-O2-n2
25,Ctps,5141,5519,8411,7669,7614,6353,6617,5176
51,Fhl3,485,379,1235,1582,1327,819,420,637
59,1110065P20Rik,1656,1645,2309,2508,2023,2304,1913,1823
112,C77080,2177,1840,621,881,1095,1434,1211,2144
136,Tinagl1,4808,3619,17673,23864,23859,14605,7335,7516
...,...,...,...,...,...,...,...,...,...
14949,Utp14b,2904,2616,1765,1516,1709,1517,2078,2527
15004,Ttc39aos1,66,71,221,269,226,196,115,90
15035,Pik3r3,11631,10191,5624,5268,4977,6165,6920,7135
15067,Dock10,490,578,259,110,273,128,254,289
15091,Slc2a1,16758,14628,21291,32525,19904,23827,16493,19999

In [339]:
normalized.index = normalized.loc[:,"Id"]
normalized

,Id,norm.5.0-O2-n1,norm.5.0-O2-n2,norm.0.1-O2-n1,norm.0.1-O2-n2,norm.0.5-O2-n1,norm.0.5-O2-n2,norm.1.0-O2-n1,norm.1.0-O2-n2
Id,,,,,,,,,
Ctps,Ctps,5141,5519,8411,7669,7614,6353,6617,5176
Fhl3,Fhl3,485,379,1235,1582,1327,819,420,637
1110065P20Rik,1110065P20Rik,1656,1645,2309,2508,2023,2304,1913,1823
C77080,C77080,2177,1840,621,881,1095,1434,1211,2144
Tinagl1,Tinagl1,4808,3619,17673,23864,23859,14605,7335,7516
...,...,...,...,...,...,...,...,...,...
Utp14b,Utp14b,2904,2616,1765,1516,1709,1517,2078,2527
Ttc39aos1,Ttc39aos1,66,71,221,269,226,196,115,90
Pik3r3,Pik3r3,11631,10191,5624,5268,4977,6165,6920,7135
Dock10,Dock10,490,578,259,110,273,128,254,289
Slc2a1,Slc2a1,16758,14628,21291,32525,19904,23827,16493,19999

In [340]:
good_value = normalized.loc[:,"norm.5.0-O2-n1":"norm.1.0-O2-n2"]
good_value

,norm.5.0-O2-n1,norm.5.0-O2-n2,norm.0.1-O2-n1,norm.0.1-O2-n2,norm.0.5-O2-n1,norm.0.5-O2-n2,norm.1.0-O2-n1,norm.1.0-O2-n2
Id,,,,,,,,
Ctps,5141,5519,8411,7669,7614,6353,6617,5176
Fhl3,485,379,1235,1582,1327,819,420,637
1110065P20Rik,1656,1645,2309,2508,2023,2304,1913,1823
C77080,2177,1840,621,881,1095,1434,1211,2144
Tinagl1,4808,3619,17673,23864,23859,14605,7335,7516
...,...,...,...,...,...,...,...,...
Utp14b,2904,2616,1765,1516,1709,1517,2078,2527
Ttc39aos1,66,71,221,269,226,196,115,90
Pik3r3,11631,10191,5624,5268,4977,6165,6920,7135
Dock10,490,578,259,110,273,128,254,289
Slc2a1,16758,14628,21291,32525,19904,23827,16493,19999